version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-tracker-backend
    ports:
      - "3000:3000"
    volumes:
      - job-tracker-data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=

volumes:
  job-tracker-data:
