version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-tracker-backend
    ports:
      - "8070:8070"
    volumes:
      - job-tracker-data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8070

volumes:
  job-tracker-data:
